[2024-09-06T00:00:07.984+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-06T00:00:08.050+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v3.second_task scheduled__2024-09-05T00:00:00+00:00 [queued]>
[2024-09-06T00:00:08.081+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v3.second_task scheduled__2024-09-05T00:00:00+00:00 [queued]>
[2024-09-06T00:00:08.090+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-06T00:00:08.131+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): second_task> on 2024-09-05 00:00:00+00:00
[2024-09-06T00:00:08.161+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=27599) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-06T00:00:08.176+0000] {standard_task_runner.py:72} INFO - Started process 27607 to run task
[2024-09-06T00:00:08.178+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v3', 'second_task', 'scheduled__2024-09-05T00:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp2_md8vzi']
[2024-09-06T00:00:08.191+0000] {standard_task_runner.py:105} INFO - Job 163: Subtask second_task
[2024-09-06T00:00:08.318+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_v3.second_task scheduled__2024-09-05T00:00:00+00:00 [running]> on host 626f2e28dec2
[2024-09-06T00:00:08.488+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abhay' AIRFLOW_CTX_DAG_ID='my_first_dag_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-05T00:00:00+00:00'
[2024-09-06T00:00:08.491+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-06T00:00:08.516+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-06T00:00:08.520+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the second task!']
[2024-09-06T00:00:08.558+0000] {subprocess.py:86} INFO - Output:
[2024-09-06T00:00:08.565+0000] {subprocess.py:93} INFO - I am the second task!
[2024-09-06T00:00:08.570+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-06T00:00:08.652+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-06T00:00:08.654+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v3, task_id=second_task, run_id=scheduled__2024-09-05T00:00:00+00:00, execution_date=20240905T000000, start_date=20240906T000008, end_date=20240906T000008
[2024-09-06T00:00:08.728+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-06T00:00:08.759+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-06T00:00:08.778+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
