[2024-09-02T16:17:01.252+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T16:17:01.264+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task manual__2024-09-02T16:16:59.464377+00:00 [queued]>
[2024-09-02T16:17:01.270+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task manual__2024-09-02T16:16:59.464377+00:00 [queued]>
[2024-09-02T16:17:01.271+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-09-02T16:17:01.278+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): second_task> on 2024-09-02 16:16:59.464377+00:00
[2024-09-02T16:17:01.283+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4012) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-02T16:17:01.283+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'second_task', 'manual__2024-09-02T16:16:59.464377+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp9507r6ka']
[2024-09-02T16:17:01.285+0000] {standard_task_runner.py:72} INFO - Started process 4013 to run task
[2024-09-02T16:17:01.286+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask second_task
[2024-09-02T16:17:01.317+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.second_task manual__2024-09-02T16:16:59.464377+00:00 [running]> on host cedbab6b7256
[2024-09-02T16:17:01.361+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abhay' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T16:16:59.464377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T16:16:59.464377+00:00'
[2024-09-02T16:17:01.362+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T16:17:01.372+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-02T16:17:01.373+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the second task!']
[2024-09-02T16:17:01.380+0000] {subprocess.py:86} INFO - Output:
[2024-09-02T16:17:01.381+0000] {subprocess.py:93} INFO - I am the second task!
[2024-09-02T16:17:01.382+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-02T16:17:01.398+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T16:17:01.399+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, run_id=manual__2024-09-02T16:16:59.464377+00:00, execution_date=20240902T161659, start_date=20240902T161701, end_date=20240902T161701
[2024-09-02T16:17:01.421+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-02T16:17:01.455+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-02T16:17:01.467+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
