[2024-09-08T17:22:20.198+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-08T17:22:20.208+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_dag_v2.task1 scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T17:22:20.213+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_dag_v2.task1 scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T17:22:20.214+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 4
[2024-09-08T17:22:20.228+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): task1> on 2024-09-07 00:00:00+00:00
[2024-09-08T17:22:20.236+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4417) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-08T17:22:20.237+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'catchup_dag_v2', 'task1', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpk68yingn']
[2024-09-08T17:22:20.240+0000] {standard_task_runner.py:72} INFO - Started process 4418 to run task
[2024-09-08T17:22:20.241+0000] {standard_task_runner.py:105} INFO - Job 254: Subtask task1
[2024-09-08T17:22:20.286+0000] {task_command.py:467} INFO - Running <TaskInstance: catchup_dag_v2.task1 scheduled__2024-09-07T00:00:00+00:00 [running]> on host 626f2e28dec2
[2024-09-08T17:22:20.334+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abhay' AIRFLOW_CTX_DAG_ID='catchup_dag_v2' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-09-08T17:22:20.336+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-08T17:22:20.345+0000] {logging_mixin.py:190} INFO - hello
[2024-09-08T17:22:20.346+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-08T17:22:20.352+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-08T17:22:20.353+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=catchup_dag_v2, task_id=task1, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20240908T172220, end_date=20240908T172220
[2024-09-08T17:22:20.376+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-08T17:22:20.386+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T17:22:20.388+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
