[2024-09-08T17:22:02.242+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-08T17:22:02.287+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_dag_v1.task1 scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-09-08T17:22:02.305+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_dag_v1.task1 scheduled__2024-09-06T00:00:00+00:00 [queued]>
[2024-09-08T17:22:02.306+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 4
[2024-09-08T17:22:02.356+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): task1> on 2024-09-06 00:00:00+00:00
[2024-09-08T17:22:02.366+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4396) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-08T17:22:02.376+0000] {standard_task_runner.py:72} INFO - Started process 4402 to run task
[2024-09-08T17:22:02.406+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'catchup_dag_v1', 'task1', 'scheduled__2024-09-06T00:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpanuhrxb2']
[2024-09-08T17:22:02.416+0000] {standard_task_runner.py:105} INFO - Job 252: Subtask task1
[2024-09-08T17:22:03.257+0000] {task_command.py:467} INFO - Running <TaskInstance: catchup_dag_v1.task1 scheduled__2024-09-06T00:00:00+00:00 [running]> on host 626f2e28dec2
[2024-09-08T17:22:03.559+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abhay' AIRFLOW_CTX_DAG_ID='catchup_dag_v1' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-06T00:00:00+00:00'
[2024-09-08T17:22:03.562+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-08T17:22:03.623+0000] {logging_mixin.py:190} INFO - hello
[2024-09-08T17:22:03.625+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-08T17:22:03.634+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-08T17:22:03.635+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=catchup_dag_v1, task_id=task1, run_id=scheduled__2024-09-06T00:00:00+00:00, execution_date=20240906T000000, start_date=20240908T172202, end_date=20240908T172203
[2024-09-08T17:22:03.710+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-08T17:22:03.726+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T17:22:03.727+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
